import { MenuItem } from './types';

export const CATEGORIES = [
  'All',
  'Pizza',
  'Pasta',
  'Starters',
  'Salads',
  'Desserts',
  'Main Courses',
  'Cigarettes',
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Margherita Pizza',
    description: 'Classic pizza with fresh mozzarella, tomatoes, and basil.',
    price: 850,
    imageUrl: 'https://picsum.photos/seed/margherita/400/300',
    category: 'Pizza',
  },
  {
    id: '2',
    name: 'Pepperoni Pizza',
    description: 'A crowd favorite with spicy pepperoni and melted cheese.',
    price: 950,
    imageUrl: 'https://picsum.photos/seed/pepperoni/400/300',
    category: 'Pizza',
  },
  {
    id: '3',
    name: 'Spaghetti Carbonara',
    description: 'Creamy pasta with pancetta, egg yolk, and parmesan cheese.',
    price: 750,
    imageUrl: 'https://picsum.photos/seed/carbonara/400/300',
    category: 'Pasta',
  },
  {
    id: '4',
    name: 'Garlic Bread',
    description: 'Toasted bread with garlic, butter, and herbs.',
    price: 350,
    imageUrl: 'https://picsum.photos/seed/garlicbread/400/300',
    category: 'Starters',
  },
  {
    id: '5',
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce with Caesar dressing, croutons, and parmesan.',
    price: 600,
    imageUrl: 'https://picsum.photos/seed/caesar/400/300',
    category: 'Salads',
  },
  {
    id: '6',
    name: 'Tiramisu',
    description: 'A classic Italian dessert with coffee-soaked ladyfingers.',
    price: 500,
    imageUrl: 'https://picsum.photos/seed/tiramisu/400/300',
    category: 'Desserts',
  },
  {
    id: '7',
    name: 'Grilled Chicken Steak',
    description: 'Tender chicken breast grilled to perfection, served with vegetables.',
    price: 1100,
    imageUrl: 'https://picsum.photos/seed/chickensteak/400/300',
    category: 'Main Courses',
  },
  {
    id: '8',
    name: 'Marlboro Lights',
    description: 'A pack of 20 premium cigarettes.',
    price: 400,
    imageUrl: 'https://picsum.photos/seed/marlboro/400/300',
    category: 'Cigarettes',
  },
   {
    id: '9',
    name: 'Fettuccine Alfredo',
    description: 'Rich and creamy Alfredo sauce over tender fettuccine pasta.',
    price: 800,
    imageUrl: 'https://picsum.photos/seed/alfredo/400/300',
    category: 'Pasta',
  },
  {
    id: '10',
    name: 'Bruschetta',
    description: 'Toasted bread topped with fresh tomatoes, garlic, basil, and olive oil.',
    price: 450,
    imageUrl: 'https://picsum.photos/seed/bruschetta/400/300',
    category: 'Starters',
  },
  {
    id: '11',
    name: 'Veggie Supreme Pizza',
    description: 'Loaded with bell peppers, onions, olives, mushrooms, and cheese.',
    price: 900,
    imageUrl: 'https://picsum.photos/seed/veggiepizza/400/300',
    category: 'Pizza',
  },
  {
    id: '12',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with a gooey, molten center.',
    price: 550,
    imageUrl: 'https://picsum.photos/seed/lavacake/400/300',
    category: 'Desserts',
  }
];